### PR TITLE
Provide go/analysis analyzer instance

### PR DESCRIPTION
**Pull request by dtcaciuc**
This PR partially addresses #165, i.e. it provides an Analyzer but does not rework the internals around it yet.

### CODE REVIEW

**Comment by dtcaciuc** [comment]
Existing tests were copied and are largely unchanged. They are adapted to syntax required by the testing utility package https://pkg.go.dev/golang.org/x/tools@v0.1.0/go/analysis/analysistest. Separate test cases were added to test individual enabled flags.

**Review by echlebek — COMMENTED** [review]
Just curious, why the package-scoped variable, rather than a way to produce an analyzer with a function?

**Comment by dtcaciuc** [comment]
This seems to be the suggested way to organize things. See
***@***.***#hdr-Analyzer

**Comment by echlebek** [comment]
Should we merge this as is, and make another issue to migrate the internals?

**Comment by dtcaciuc** [comment]
Not sure if it constitutes migration, but it should be possible to simplify the code to record raw token.Pos rather than immediately resolve it into file & line with addErrorAtPosition() whenever we find an error as its done now. Then after the visitor is done running, either feed that directly into go/analysis function output or convert to file/line and write to errcheck program output.

I'll take the PR out of draft.

**Pull request merged**
