### PR TITLE
Update for upstream API change.

### LINKED ISSUE #62: Errcheck.go line 74
github.com/kisielk/errcheck/internal/errcheck.go:74: unknown loader.Config field 'SourceImports' in struct literal

Sorry for not sending a merge request. I am still trying to figure out how to write code. But go the following error while installing vim-go

### PR DESCRIPTION
**Pull request by shurcooL**
Related to golang/tools@69db398.

Resolves #62.

### CODE REVIEW

**Comment by zimmski** [comment]
I tested it and it looks good to me.

**Comment by zimmski** [comment]
I just read the documentation of then SourceImports now ImportFromBinary. I think we can solve #56 by using `ImportFromBinary: true` and by compiling missing dependencies. At least one of my projects goes from ~1.0s to ~0.3s.

**Comment by shurcooL** [comment]
Perhaps. It might not be trivial though. Note this option has existed in the past, that hasn't changed.

In any case, it falls outside of the scope of this PR. The goal here is to allow the package to compile while preserving previous behavior.

**Comment by zimmski** [comment]
Right. should have mentioned it in the other issue, sorry.

**Comment by kisielk** [comment]
Thanks for the fix :+1: Let's move discussion of the other thing to the other issue.

**Pull request merged**
