### PR TITLE
Maintain a list of stdlib functions with irrelevant errors

### PR DESCRIPTION
**Pull request by dominikh**
~~Either I don't understand the tests, or they're flawed. No matter what marker I did or did not place behind the newly added test cases, the tests always pass. They even pass when I removed the ignores and should've gotten more unchecked errors than expected.~~

### CODE REVIEW

**Comment by kisielk** [comment]
Are you sure you're running the tests for `internal/errcheck` ? There are two test suites, one that tests the main program and another that tests the internal package.

**Comment by dominikh** [comment]
Well, I am sure I was *not* running the tests for internal/errcheck… I still have no idea what ASSERT and BLANK stand for, but it looks like I don't need to care since using no marker at all does what I want.

**Comment by dominikh** [comment]
@kisielk Do we still actively support Go 1.5, i.e. should I find another package-level example instead of math/rand.Read?

**Comment by kisielk** [comment]
BLANK is for when the option to check assignments to the blank identifier is turned on. ASSERT checks for type assertions without error checks. You don't need to care for either of those.

As for go1.5 support, I think we'll probably need test cases for different versions of Go anyway since there are probably different API calls we'll want to ignore and test? I guess we should make the list first and see how many of those there are before bothering with that though.

**Comment by dominikh** [comment]
Well, it's unlikely that a function will return a meaningful error in one version and none in another. Apart from that, the implementation doesn't care if the functions even exist, they're strings in a map. And in the unit tests I think it's safe to only test a small subset, to make sure that the overall logic works. I wouldn't add each and every ignored function in the tests.

**Comment by kisielk** [comment]
I was thinking more of new stuff added to the stdlib which implements an interface that returns an error but the type itself does not.

**Comment by kisielk** [comment]
It would be nice to test an exhaustive list, but maybe not necessary.

Also need to test what happens when assigned to an interface.

**Comment by dominikh** [comment]
Assigned to an interface does the obvious thing: We have no idea what the underlying type is (without more advanced analysis), so it won't match the ignore filter.

**Comment by kisielk** [comment]
That's what I assumed.

I saw the comment about vendored packages. I don't think we need to worry about this. I think in the future we'll just expand the whitelist facility so people can add their own. I'd like to replace the regexp based ignores.

**Comment by kisielk** [comment]
Have you checked if it works with import aliases?

**Comment by dominikh** [comment]
What do you mean by import aliases? If you mean `import foo "bar"`, then that has no effect on the actual import path, only the package name, which isn't considered in `FullName`.

**Comment by kisielk** [comment]
That is what I meant. I guess if we know for sure it works and that the implementation won't change then we don't need a test, but it wouldn't be hard to add one..

**Comment by dominikh** [comment]
Added another test. Still using math/rand for now, couldn't find another suitable package function. Removed the WIP/do not merge note.

**Comment by kisielk** [comment]
I think math.Rand.Read should be available in go1.5, could test with that instead.

**Comment by dominikh** [comment]
The point was to test a package-level function, in addition to checking methods via bytes.Buffer. And no, math.Rand.Read didn't exist in 1.5 either. Both were added in 1.6.

**Comment by kisielk** [comment]
I guess we can probably just drop support for 1.5. It's pretty old at this point.

**Comment by kisielk** [comment]
So should we merge this?

**Comment by tamird** [comment]
off topic, but @dominikh do you think reimplementing errcheck in terms of https://godoc.org/honnef.co/go/lint/lintutil would be worthwhile?

**Comment by dominikh** [comment]
@kisielk: If you're happy with the code then yeah, we can merge it.

@tamird: Let's put it this way: It should be possible. errcheck wouldn't stand to gain much from it, though, other than the advantage that you mentioned. Please file a separate issue if you'd like to discuss it further :-)

**Pull request merged**
