### PR TITLE
Fix internal package directory structure

### PR DESCRIPTION
**Pull request by tuxychandru**
The package present in the internal directory is named errcheck, but is
not present in a subdirectory. `go get github.com/kisielk/errcheck`
fails on go tip due to this.

This change places the files belonging to the internal errcheck package
in a subdirectory of internal and makes it follow the internal package
convention to be introduced in go 1.5.

### CODE REVIEW

**Comment by kisielk** [comment]
Thanks for fixing tha :) Forgot they had made that change for 1.5

**Comment by shurcooL** [comment]
> The package present in the internal directory is named errcheck, but is
not present in a subdirectory. `go get github.com/kisielk/errcheck`
fails on go tip due to this.

@tuxychandru, can you share what the error message was when it fails?

/cc @slimsag This finding looks relevant.

**Comment by tuxychandru** [comment]
@shurcooL 

```
package github.com/kisielk/errcheck
	imports github.com/kisielk/errcheck/internal
	imports github.com/kisielk/errcheck/internal
	imports github.com/kisielk/errcheck/internal: use of internal package not allowed
```

**Comment by shurcooL** [comment]
Thank you.

@slimsag, looks like we'll want to change https://github.com/sourcegraph/go-vcs/blob/master/vcs/internal/path.go.

**Comment by tuxychandru** [comment]
There also seems to be some issue with the go tool itself. Filed this issue: https://github.com/golang/go/issues/11307

**Pull request merged**
