### PR TITLE
Add support for build tags via a new -tags flag

### PR DESCRIPTION
**Pull request by autarch**
I also updated the README.md to include docs on this and the -asserts flag.

### CODE REVIEW

**Comment by kisielk** [comment]
I think it would be good to separate the tags by spaces, like the regular go command does.

I know some of the other list options separate by commas, but I think that was a mistake that should probably be fixed.

**Comment by autarch** [comment]
I agree. I was just following along with the existing code ;)

**Comment by autarch** [comment]
I'll rework the PR.

**Comment by kisielk** [comment]
I know you were, but I would say that code was a mistake on my part ;)

**Comment by autarch** [comment]
Ok, I've updated this to use multiple `-tags` flags. I also realized this wasn't quite done, as I'd done the flag parsing, but the setting build tags in the loader config was hard-coding the "testing" tag we needed internally. Oops.

**Comment by kisielk** [comment]
That's still not quite the way to go cmd works.. it just takes one space-separate argument:

`-tags 'foo bar !baz'` for example.

Have a look at the source of `src/cmd/go/build.go` for how they do that..  It would be good if we handled it exactly the same otherwise people are going to get confused / frustrated.

**Comment by shurcooL** [comment]
> Have a look at the source of `src/cmd/go/build.go` for how they do that.. It would be good if we handled it exactly the same otherwise people are going to get confused / frustrated.

Highly agreed.

**Comment by autarch** [comment]
I agree too. I didn't realize that `go` was doing that. It's kind of gross, but consistency trumps beauty.

**Comment by autarch** [comment]
Alright, I redid the parsing to parse a space-separated string. I also added tests using the [assert](http://godoc.org/github.com/stretchr/testify/assert) package, which provides much better diagnostics than I wanted to write up by hand. I made a second commit to convert the existing tests to using it as well, but I can remove that if you like.

**Comment by kisielk** [comment]
Thanks. I don't really  want to depend on another external library just for tests so I rewrote the tests just the testing package. I merged the work in to the "tags" branch in this repo. There's some more cleanup I want to do with regards to option setting, it's getting a little unwieldy so it's time to do some refactoring before merging this in.

**Comment by kisielk** [comment]
Now that I did a bunch of refactoring work on options, the changes are now in master.

**Pull request closed without merging**
