### PR TITLE
Limit the amount of memory errcheck uses with smarter goroutine scheduling

### PR DESCRIPTION
**Pull request by dragonsinth**
We have >700 packages we're running errcheck on, and this is blowing up our build on CircleCI, which is limited to ~4G of memory.

We can hack around this using `xargs` to invoke `errcheck` in batches, but this takes several times longer to run end-to-end as a lot of work is thrown away.

After looking at the code, it looks like there's a super simple fix to make errcheck scale much better in terms of memory without sacrificing throughput.

### CODE REVIEW

**Comment by dragonsinth** [comment]
Not sure what's up with the test failures, but Go 1.14 seems broken on master.

**Comment by kisielk** [comment]
Thanks, looks good to me. We've fixed the builds on master, can you rebase your PR so the tests can run?

**Comment by dragonsinth** [comment]
rebased!

**Comment by kisielk** [comment]
Great, thanks for the change!

**Pull request merged**
